### ISSUE TITLE
Admins and boards

### ISSUE THREAD

**Issue by 00markin** [xrystalll/MERN-Forum#2]
how do you upgrade an user to an Admin, and how do you create a new board?

**Comment by xrystalll** [comment]
To assign a user as an administrator, you need to set the value for the role "3" in the database. The ability to create boards will be available after assigning a role.
Later, you do not have to give roles through the database, since the administrator can give roles through the profile.

**Comment by 00markin** [comment]
After try that, I saw the dashboard, it's perfect, ty so much @xrystalll
