### ISSUE TITLE
Not able to load boards

### ISSUE THREAD

**Issue by Vansh1067** [xrystalll/MERN-Forum#3]
When i try to create new board so it show me a error borad is not loaded
![screencapture-localhost-3000-boards-2021-11-11-16_43_47](https://user-images.githubusercontent.com/50477887/141288719-d4b730e0-61f2-45b5-bd32-9a990f2ecef1.png)

**Comment by Vansh1067** [comment]
Tell me the procedure for adding the boards

**Comment by xrystalll** [comment]
@Vansh1067 
First you need to become an administrator. Then the control panel will be available.
Check this answer - https://github.com/xrystalll/MERN-Forum/issues/2#issuecomment-904544387

**Comment by Vansh1067** [comment]
How I can became a administration
