### ISSUE TITLE
How to create a new board?

### ISSUE THREAD

**Issue by KennethAshworth** [xrystalll/MERN-Forum#6]
I made myself an admin via updating my role with mongodb compass, but I still cant get a "create new board" button to show up. I am trying to make a thread, but since there are no boards to select it prevents me from posting the thread.

**Comment by xrystalll** [comment]
Dashboard / Boards/ Create new board

**Comment by KennethAshworth** [comment]
Yes! thank you for that. Upon looking at it again this morning I tried logging out and back in and the dashboard showed up. My user data must have been cached locally xD
