### ISSUE TITLE
Authorization History search in admin returns no results?

### ISSUE THREAD

**Issue by KennethAshworth** [xrystalll/MERN-Forum#7]
I am trying to understand what the authorization history is used for and why I would search against it as an admin? Currently it seems to never returns any results. I see the logged data that shows up in mongoDB. Also wondering what this type of data is used for in a forum administration context?

**Comment by xrystalll** [comment]
Protection from bad people who can spam or something else, and after the ban, register a new account) Through the history of authorizations, you can compare the data of suspicious users.

**Comment by KennethAshworth** [comment]
Ok that makes sense. I will have to play around with it more to get a better feel of it.
